### PR TITLE
python-generator: Fix indentation on suites with error cases

### PR DESCRIPTION
**Pull request by cmccandless**
Also, add yapf style configuration.

### CODE REVIEW

**Comment by yawpitch** [comment]
Hmm... more than a little hesitant to introduce a custom yapf configuration, especially to try and correct solely for non-syntactically important whitespace.

Basically I'm just going to end up chasing my own tail over syntactically unimportant spacing, there's enough difficulty getting the important indentation correct, cleaning up the results into something reasonably readable is the argument for using `yapf` to begin with, to bring the generated test file at least up to a decent, workable pep-8 standards.

Arguably if the pre-existing test file differs only on white space we should probably run `yapf` on the existing file and see if we weren't using an unreasonable standard all along. Where there's a true functionality issue we can `# yapf: disable` a block, then strip those tags post-autoformat, but I'm not aware of a functional reason why the version string needs a specific amount of whitespace above or below it.

**Comment by cmccandless** [comment]
> Hmm... more than a little hesitant to introduce a custom yapf configuration

I can back that commit out if you wish, but that file is just the verbatim output of `yapf --style-help`. It's the defaults, but explicit. 

> but I'm not aware of a functional reason why the version string needs a specific amount of whitespace above or below it.

I don't believe there is one really; this is just for consistency with the existing test suites. I suppose we could switch to whatever yapf outputs.

**Comment by yawpitch** [comment]
> I can back that commit out if you wish, but that file is just the verbatim output of `yapf --style-help`. It's the defaults, but explicit.

Yeah, let's not stick with their default styles ... yapf configuration just becomes an extra thread to pull on.

> I don't believe there is one really; this is just for consistency with the existing test suites. I suppose we could switch to whatever yapf outputs.

Considering the lack of consistency between the existing suites, I'd say taking a variable out of the equation is a good idea, and they won't exactly suffer from being reformatted. It also gives me less of a drifting target to try and hit.

**Comment by cmccandless** [comment]
I've removed the commit that added the default style.

> It also gives me less of a drifting target to try and hit.

:+1:

**Comment by yawpitch** [comment]
Hey, I'm going to reject this one. Ended up backing out most of the manual whitespace fixes in the template and adding back in only the minimum. Also fixed the exception handling at the same time.

**Pull request closed without merging**
